/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(e.htwdd.sf.beleg.lang.LangPackage.eINSTANCE);
		return result;
	}
}
