/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86379s87568.ui.internal.S86379s87568Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S86379s87568Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S86379s87568Activator activator = S86379s87568Activator.getInstance();
		return activator != null ? activator.getInjector(S86379s87568Activator.E_HTWDD_SF_BELEG_LANG) : null;
	}

}
