/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LangUiModule extends AbstractLangUiModule {

	public LangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
