/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class LangProposalProvider extends AbstractLangProposalProvider {
}
