/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLangScopeProvider extends DelegatingScopeProvider {
}
