/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86379s87568.ui.internal.S86379s87568Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S86379s87568Activator.getInstance().getInjector("e.htwdd.sf.beleg.Lang");
	}

}
