/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class LangScopeProvider extends AbstractLangScopeProvider {

}
