/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class LangOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
