/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import e.htwdd.sf.beleg.LangRuntimeModule;
import e.htwdd.sf.beleg.LangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LangIdeSetup extends LangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LangRuntimeModule(), new LangIdeModule()));
	}
	
}
