/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.parser.antlr;

import com.google.inject.Inject;
import e.htwdd.sf.beleg.parser.antlr.internal.InternalLangParser;
import e.htwdd.sf.beleg.services.LangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LangParser extends AbstractAntlrParser {

	@Inject
	private LangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLangParser createParser(XtextTokenStream stream) {
		return new InternalLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public LangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
