/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("e/htwdd/sf/beleg/parser/antlr/internal/InternalLang.tokens");
	}
}
