/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import e.htwdd.sf.beleg.lang.Gain;
import e.htwdd.sf.beleg.lang.InfWithZu;
import e.htwdd.sf.beleg.lang.Title;
import e.htwdd.sf.beleg.lang.UserStories;
import e.htwdd.sf.beleg.lang.UserStory;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class LangLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public LangLabelProvider(AdapterFactoryLabelProvider delegate) { 
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	private String toInfinitive(InfWithZu verb) {
		if (verb.getInf() != null)
			return verb.getInf();
		else {
			return verbWithoutZu(verb.getWith_embedded_zu());
		}
	}
	
	private String verbWithoutZu(String verb) { 
		String withoutZu = null;
		final int idx = verb.lastIndexOf("zu");
		if ((idx >= 0)) {
			String prefix = verb.substring(0, idx);
			String suffix = verb.substring((idx + 2)); 
			withoutZu = prefix + suffix;
		} 
		return withoutZu;
	}


	String text(UserStories ele) {
		return "Userstories";
	}

	String text(UserStory ele) { 
	    String label = "Userstory";
		return label;
	} 
	
	String text(Title ele) {
		String label = "Title";
		return label;
	}
	
	String text(Gain ele) {
		return "Gain";
	} 
	
	String text(InfWithZu ele) {
		return "infinitiv: " + toInfinitive(ele);
	}
}
