/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import e.htwdd.sf.beleg.lang.Gain;
import e.htwdd.sf.beleg.lang.Goal;
import e.htwdd.sf.beleg.lang.Userstories;
import e.htwdd.sf.beleg.lang.Userstory;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class LangLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public LangLabelProvider(AdapterFactoryLabelProvider delegate) { 
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	
	
	String text(Userstories ele) {
		return "Userstories";
	}

	String text(Userstory ele) { 
	    String label = "Userstory: title= " + ele.getTitle() + " role=" + ele.getRole();
		return label;
	} 
	
	String text(Goal ele) {
		return "Goal: " + ele.getWords();
	} 
	String text(Gain ele) {
		return "Gain: " + ele.getWords();
	} 
	
}
