/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg.validation;

import org.eclipse.xtext.validation.Check;

import e.htwdd.sf.beleg.lang.Gain;
import e.htwdd.sf.beleg.lang.InfWithZu;
import e.htwdd.sf.beleg.lang.LangPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class LangValidator extends AbstractLangValidator {
	
	private boolean isValidEmbeddedZu(String verb) {
		if (verb == null)
			return false;
		
		
		int pos = verb.lastIndexOf("zu");
		if (pos == 0 | pos == -1)
			return false;
		
		return true;
	}
	
    @Check
    public void checkInfWithEmbeddedZuHasEmbeddedZu(InfWithZu inf) {
    	
    	String verb = inf.getWith_embedded_zu();
    	System.out.println(verb);
    	if (verb == null)
    		return; 
    	else if (!isValidEmbeddedZu(verb)) {
            warning("Das verb muss ein Infinitiv mit \'zu\' sein", 
                LangPackage.Literals.INF_WITH_ZU__WITH_EMBEDDED_ZU); 
    	}
    } 
}
