/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LangRuntimeModule extends AbstractLangRuntimeModule {
}
