/*
 * generated by Xtext 2.41.0.M1
 */
package e.htwdd.sf.beleg;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LangStandaloneSetup extends LangStandaloneSetupGenerated {

	public static void doSetup() {
		new LangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
