grammar e.htwdd.sf.beleg.Lang with org.eclipse.xtext.common.Terminals

generate lang "http://www.htwdd.e/sf/beleg/Lang"

Model:
	Userstories;

Userstories: 
	userstories+=Userstory+
;

Userstory: 
 	title+=ID+ ':' 'Als' role+=ID+ 'möchte' 'ich' goal=Goal ',' 'um' gain=Gain '.'
; 

Goal: words+=ID+ ; 

Gain:
	words+=ID+ ;

terminal ID: '^'?('a'..'z'|'A'..'Z'|'ä'|'ö'|'ü'|'ß'|'Ä'|'Ö'|'Ü'|'_')
            ('a'..'z'|'A'..'Z'|'ä'|'ö'|'ü'|'ß'|'Ä'|'Ö'|'Ü'|'_'|'0'..'9')*;
